In [1]:
# Importing libraries 

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
# Importing data

path = r'C:\Users\katro\Instacart Basket Analysis'

In [3]:
df_ords = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'data_combined.pkl'))

In [4]:
df_ords.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,...,median_of_orders,frequency_flag,first_name,surname,gender,state,age,n_dependants,fam_status,income
0,2539329,1,1,2,8,11.11484,196,1,0,both,...,20.0,Regular customer,Linda,Nguyen,Female,Alabama,31,3,married,40423
1,2539329,1,1,2,8,11.11484,14084,2,0,both,...,20.0,Regular customer,Linda,Nguyen,Female,Alabama,31,3,married,40423
2,2539329,1,1,2,8,11.11484,12427,3,0,both,...,20.0,Regular customer,Linda,Nguyen,Female,Alabama,31,3,married,40423
3,2539329,1,1,2,8,11.11484,26088,4,0,both,...,20.0,Regular customer,Linda,Nguyen,Female,Alabama,31,3,married,40423
4,2539329,1,1,2,8,11.11484,26405,5,0,both,...,20.0,Regular customer,Linda,Nguyen,Female,Alabama,31,3,married,40423

In [6]:
# Removing PII

df_ords = df_ords.drop(columns = ['first_name'])

In [7]:
df_ords = df_ords.drop(columns = ['surname'])

In [8]:
# Creating region flag

result = []
for value in df_ords["state"]:
    if value == 'Maine':
        result.append("Northeast")
    elif value == 'New Hampshire':
        result.append("Northeast")
    elif value == 'Vermont':
        result.append("Northeast")
    elif value == 'Massachusetts':
        result.append("Northeast")
    elif value == 'Rhode Island':
        result.append("Northeast")
    elif value == 'Connecticut':
        result.append("Northeast")
    elif value == 'New York':
        result.append("Northeast")
    elif value == 'Pennsylvania':
        result.append("Northeast")
    elif value == 'New Jersey':
        result.append("Northeast")
    elif value == 'Wisconsin':
        result.append("Midwest")
    elif value == 'Michigan':
        result.append("Midwest")
    elif value == 'Illinois':
        result.append("Midwest")
    elif value == 'Indiana':
        result.append("Midwest")
    elif value == 'Ohio':
        result.append("Midwest")
    elif value == 'South Dakota':
        result.append("Midwest")
    elif value == 'North Dakota':
        result.append("Midwest")
    elif value == 'Nebraska':
        result.append("Midwest")
    elif value == 'Kansas':
        result.append("Midwest")
    elif value == 'Minnesota':
        result.append("Midwest")
    elif value == 'Iowa':
        result.append("Midwest")
    elif value == 'Missouri':
        result.append("Midwest")
    elif value == 'Idaho':
        result.append("West")
    elif value == 'Montana':
        result.append("West")
    elif value == 'Wyoming':
        result.append("West")
    elif value == 'Nevada':
        result.append("West")
    elif value == 'Utah':
        result.append("West")
    elif value == 'Colorado':
        result.append("West")
    elif value == 'New Mexico':
        result.append("West")
    elif value == 'Arizona':
        result.append("West")
    elif value == 'Alaska':
        result.append("West")
    elif value == 'Washington':
        result.append("West")
    elif value == 'Oregon':
        result.append("West")
    elif value == 'California':
        result.append("West")
    elif value == 'Hawaii':
        result.append("West")
    else:
        result.append("South")

In [9]:
result

['South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'Northeast',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'South',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 'West',
 ...]

In [10]:
# Creating region column

df_ords['region'] = result

In [11]:
df_ords.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,...,spending_flag,median_of_orders,frequency_flag,gender,state,age,n_dependants,fam_status,income,region
0,2539329,1,1,2,8,11.11484,196,1,0,both,...,Low spender,20.0,Regular customer,Female,Alabama,31,3,married,40423,South
1,2539329,1,1,2,8,11.11484,14084,2,0,both,...,Low spender,20.0,Regular customer,Female,Alabama,31,3,married,40423,South
2,2539329,1,1,2,8,11.11484,12427,3,0,both,...,Low spender,20.0,Regular customer,Female,Alabama,31,3,married,40423,South
3,2539329,1,1,2,8,11.11484,26088,4,0,both,...,Low spender,20.0,Regular customer,Female,Alabama,31,3,married,40423,South
4,2539329,1,1,2,8,11.11484,26405,5,0,both,...,Low spender,20.0,Regular customer,Female,Alabama,31,3,married,40423,South

In [60]:
# Exporting data

df_ords.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'data_combined_2.pkl'))